package com.handy.support.mapper;

import com.handy.support.entity.Album;
import com.handy.support.entity.AlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int countByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int deleteByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int insertSelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    List<Album> selectByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    Album selectByPrimaryKey(Integer albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Album record);
}