package com.handy.support.mapper;

import com.handy.support.entity.AlbumCourse;
import com.handy.support.entity.AlbumCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    int countByExample(AlbumCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    int deleteByExample(AlbumCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    int insert(AlbumCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    int insertSelective(AlbumCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    List<AlbumCourse> selectByExample(AlbumCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AlbumCourse record, @Param("example") AlbumCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AlbumCourse record, @Param("example") AlbumCourseExample example);
}