package com.handy.support.mapper;

import com.handy.support.entity.CommentReply;
import com.handy.support.entity.CommentReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int countByExample(CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int deleteByExample(CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int insert(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int insertSelective(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    List<CommentReply> selectByExample(CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    CommentReply selectByPrimaryKey(Integer replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommentReply record, @Param("example") CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommentReply record, @Param("example") CommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentReply record);
}