package com.handy.support.mapper;

import com.handy.support.entity.CourseLabel;
import com.handy.support.entity.Label;
import com.handy.support.entity.CourseLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    int countByExample(CourseLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    int deleteByExample(CourseLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    int insert(CourseLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    int insertSelective(CourseLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    List<CourseLabel> selectByExample(CourseLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseLabel record, @Param("example") CourseLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseLabel record, @Param("example") CourseLabelExample example);






}