package com.handy.support.mapper;

import com.handy.support.entity.CourseItem;
import com.handy.support.entity.CourseItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    int countByExample(CourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    int deleteByExample(CourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    int insert(CourseItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    int insertSelective(CourseItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    List<CourseItem> selectByExample(CourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseItem record, @Param("example") CourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseItem record, @Param("example") CourseItemExample example);
}