package com.handy.support.mapper;

import com.handy.support.entity.CourseStep;
import com.handy.support.entity.CourseStepExample;
import java.util.List;

import com.handy.support.entity.Step;
import org.apache.ibatis.annotations.Param;

public interface CourseStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    int countByExample(CourseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    int deleteByExample(CourseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    int insert(CourseStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    int insertSelective(CourseStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    List<CourseStep> selectByExample(CourseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseStep record, @Param("example") CourseStepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseStep record, @Param("example") CourseStepExample example);


}