package com.handy.support.mapper;

import com.handy.support.entity.Favor;
import com.handy.support.entity.FavorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    int countByExample(FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    int deleteByExample(FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    int insert(Favor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    int insertSelective(Favor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    List<Favor> selectByExample(FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Favor record, @Param("example") FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Favor record, @Param("example") FavorExample example);
}