package com.handy.support.mapper;

import com.handy.support.entity.Hold;
import com.handy.support.entity.HoldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HoldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    int countByExample(HoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    int deleteByExample(HoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    int insert(Hold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    int insertSelective(Hold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    List<Hold> selectByExample(HoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Hold record, @Param("example") HoldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hold
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Hold record, @Param("example") HoldExample example);
}