package com.handy.support.mapper;

import com.handy.support.entity.Level;
import com.handy.support.entity.LevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int countByExample(LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int deleteByExample(LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Byte levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int insert(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int insertSelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    List<Level> selectByExample(LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    Level selectByPrimaryKey(Byte levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Level record, @Param("example") LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Level record, @Param("example") LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Level record);
}