package com.handy.support.mapper;

import com.handy.support.entity.UserLabel;
import com.handy.support.entity.UserLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    int countByExample(UserLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    int deleteByExample(UserLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    int insert(UserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    int insertSelective(UserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    List<UserLabel> selectByExample(UserLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserLabel record, @Param("example") UserLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserLabel record, @Param("example") UserLabelExample example);
}