package com.handy.support.mapper;

import com.handy.support.entity.UserAlbum;
import com.handy.support.entity.UserAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int countByExample(UserAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int deleteByExample(UserAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int insert(UserAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int insertSelective(UserAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    List<UserAlbum> selectByExample(UserAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserAlbum record, @Param("example") UserAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserAlbum record, @Param("example") UserAlbumExample example);
}