package com.handy.support.entity;

import java.util.Date;

public class AlbumCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_course.album_id
     *
     * @mbggenerated
     */
    private Integer albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_course.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_course.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    public AlbumCourse(Integer albumId, Integer courseId, Date updateTime) {
        this.albumId = albumId;
        this.courseId = courseId;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_course
     *
     * @mbggenerated
     */
    public AlbumCourse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_course.album_id
     *
     * @return the value of album_course.album_id
     *
     * @mbggenerated
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_course.album_id
     *
     * @param albumId the value for album_course.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_course.course_id
     *
     * @return the value of album_course.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_course.course_id
     *
     * @param courseId the value for album_course.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_course.update_time
     *
     * @return the value of album_course.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_course.update_time
     *
     * @param updateTime the value for album_course.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public AlbumCourse(Integer albumId, Integer courseId) {
        this.albumId = albumId;
        this.courseId = courseId;
    }
}