package com.handy.support.entity;

public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_id
     *
     * @mbggenerated
     */
    private Integer albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_name
     *
     * @mbggenerated
     */
    private String albumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_detail
     *
     * @mbggenerated
     */
    private String albumDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_state
     *
     * @mbggenerated
     */
    private Boolean albumState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public Album(Integer albumId, String albumName, String albumDetail, Boolean albumState, Integer userId) {
        this.albumId = albumId;
        this.albumName = albumName;
        this.albumDetail = albumDetail;
        this.albumState = albumState;
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_id
     *
     * @return the value of album.album_id
     *
     * @mbggenerated
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_name
     *
     * @return the value of album.album_name
     *
     * @mbggenerated
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_detail
     *
     * @return the value of album.album_detail
     *
     * @mbggenerated
     */
    public String getAlbumDetail() {
        return albumDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_state
     *
     * @return the value of album.album_state
     *
     * @mbggenerated
     */
    public Boolean getAlbumState() {
        return albumState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.user_id
     *
     * @return the value of album.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }
}