package com.handy.support.entity;

import java.util.ArrayList;
import java.util.List;

public class AlbumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public AlbumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table album
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAlbumIdIsNull() {
            addCriterion("album_id is null");
            return (Criteria) this;
        }

        public Criteria andAlbumIdIsNotNull() {
            addCriterion("album_id is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumIdEqualTo(Integer value) {
            addCriterion("album_id =", value, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdNotEqualTo(Integer value) {
            addCriterion("album_id <>", value, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdGreaterThan(Integer value) {
            addCriterion("album_id >", value, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("album_id >=", value, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdLessThan(Integer value) {
            addCriterion("album_id <", value, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdLessThanOrEqualTo(Integer value) {
            addCriterion("album_id <=", value, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdIn(List<Integer> values) {
            addCriterion("album_id in", values, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdNotIn(List<Integer> values) {
            addCriterion("album_id not in", values, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdBetween(Integer value1, Integer value2) {
            addCriterion("album_id between", value1, value2, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumIdNotBetween(Integer value1, Integer value2) {
            addCriterion("album_id not between", value1, value2, "albumId");
            return (Criteria) this;
        }

        public Criteria andAlbumNameIsNull() {
            addCriterion("album_name is null");
            return (Criteria) this;
        }

        public Criteria andAlbumNameIsNotNull() {
            addCriterion("album_name is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumNameEqualTo(String value) {
            addCriterion("album_name =", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameNotEqualTo(String value) {
            addCriterion("album_name <>", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameGreaterThan(String value) {
            addCriterion("album_name >", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameGreaterThanOrEqualTo(String value) {
            addCriterion("album_name >=", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameLessThan(String value) {
            addCriterion("album_name <", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameLessThanOrEqualTo(String value) {
            addCriterion("album_name <=", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameLike(String value) {
            addCriterion("album_name like", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameNotLike(String value) {
            addCriterion("album_name not like", value, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameIn(List<String> values) {
            addCriterion("album_name in", values, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameNotIn(List<String> values) {
            addCriterion("album_name not in", values, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameBetween(String value1, String value2) {
            addCriterion("album_name between", value1, value2, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumNameNotBetween(String value1, String value2) {
            addCriterion("album_name not between", value1, value2, "albumName");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailIsNull() {
            addCriterion("album_detail is null");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailIsNotNull() {
            addCriterion("album_detail is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailEqualTo(String value) {
            addCriterion("album_detail =", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailNotEqualTo(String value) {
            addCriterion("album_detail <>", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailGreaterThan(String value) {
            addCriterion("album_detail >", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailGreaterThanOrEqualTo(String value) {
            addCriterion("album_detail >=", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailLessThan(String value) {
            addCriterion("album_detail <", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailLessThanOrEqualTo(String value) {
            addCriterion("album_detail <=", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailLike(String value) {
            addCriterion("album_detail like", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailNotLike(String value) {
            addCriterion("album_detail not like", value, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailIn(List<String> values) {
            addCriterion("album_detail in", values, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailNotIn(List<String> values) {
            addCriterion("album_detail not in", values, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailBetween(String value1, String value2) {
            addCriterion("album_detail between", value1, value2, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumDetailNotBetween(String value1, String value2) {
            addCriterion("album_detail not between", value1, value2, "albumDetail");
            return (Criteria) this;
        }

        public Criteria andAlbumStateIsNull() {
            addCriterion("album_state is null");
            return (Criteria) this;
        }

        public Criteria andAlbumStateIsNotNull() {
            addCriterion("album_state is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumStateEqualTo(Boolean value) {
            addCriterion("album_state =", value, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateNotEqualTo(Boolean value) {
            addCriterion("album_state <>", value, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateGreaterThan(Boolean value) {
            addCriterion("album_state >", value, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("album_state >=", value, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateLessThan(Boolean value) {
            addCriterion("album_state <", value, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateLessThanOrEqualTo(Boolean value) {
            addCriterion("album_state <=", value, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateIn(List<Boolean> values) {
            addCriterion("album_state in", values, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateNotIn(List<Boolean> values) {
            addCriterion("album_state not in", values, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateBetween(Boolean value1, Boolean value2) {
            addCriterion("album_state between", value1, value2, "albumState");
            return (Criteria) this;
        }

        public Criteria andAlbumStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("album_state not between", value1, value2, "albumState");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAlbumPicIsNull() {
            addCriterion("album_pic is null");
            return (Criteria) this;
        }

        public Criteria andAlbumPicIsNotNull() {
            addCriterion("album_pic is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumPicEqualTo(String value) {
            addCriterion("album_pic =", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicNotEqualTo(String value) {
            addCriterion("album_pic <>", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicGreaterThan(String value) {
            addCriterion("album_pic >", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicGreaterThanOrEqualTo(String value) {
            addCriterion("album_pic >=", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicLessThan(String value) {
            addCriterion("album_pic <", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicLessThanOrEqualTo(String value) {
            addCriterion("album_pic <=", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicLike(String value) {
            addCriterion("album_pic like", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicNotLike(String value) {
            addCriterion("album_pic not like", value, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicIn(List<String> values) {
            addCriterion("album_pic in", values, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicNotIn(List<String> values) {
            addCriterion("album_pic not in", values, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicBetween(String value1, String value2) {
            addCriterion("album_pic between", value1, value2, "albumPic");
            return (Criteria) this;
        }

        public Criteria andAlbumPicNotBetween(String value1, String value2) {
            addCriterion("album_pic not between", value1, value2, "albumPic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table album
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table album
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}