package com.handy.support.entity;

public class Collection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.album_id
     *
     * @mbggenerated
     */
    private Integer albumId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    public Collection(Integer userId, Integer albumId) {
        this.userId = userId;
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbggenerated
     */
    public Collection() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.user_id
     *
     * @return the value of collection.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.user_id
     *
     * @param userId the value for collection.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.album_id
     *
     * @return the value of collection.album_id
     *
     * @mbggenerated
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.album_id
     *
     * @param albumId the value for collection.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }
}