package com.handy.support.entity;

import java.util.Date;

public class CommentReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reply.reply_id
     *
     * @mbggenerated
     */
    private Integer replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reply.reply_content
     *
     * @mbggenerated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reply.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reply.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reply.to_reply_id
     *
     * @mbggenerated
     */
    private Integer toReplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reply.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    public CommentReply(Integer replyId, String replyContent, String userId, Integer commentId, Integer toReplyId, Date updateTime) {
        this.replyId = replyId;
        this.replyContent = replyContent;
        this.userId = userId;
        this.commentId = commentId;
        this.toReplyId = toReplyId;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_reply
     *
     * @mbggenerated
     */
    public CommentReply() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reply.reply_id
     *
     * @return the value of comment_reply.reply_id
     *
     * @mbggenerated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reply.reply_id
     *
     * @param replyId the value for comment_reply.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reply.reply_content
     *
     * @return the value of comment_reply.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reply.reply_content
     *
     * @param replyContent the value for comment_reply.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reply.user_id
     *
     * @return the value of comment_reply.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reply.user_id
     *
     * @param userId the value for comment_reply.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reply.comment_id
     *
     * @return the value of comment_reply.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reply.comment_id
     *
     * @param commentId the value for comment_reply.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reply.to_reply_id
     *
     * @return the value of comment_reply.to_reply_id
     *
     * @mbggenerated
     */
    public Integer getToReplyId() {
        return toReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reply.to_reply_id
     *
     * @param toReplyId the value for comment_reply.to_reply_id
     *
     * @mbggenerated
     */
    public void setToReplyId(Integer toReplyId) {
        this.toReplyId = toReplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reply.update_time
     *
     * @return the value of comment_reply.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reply.update_time
     *
     * @param updateTime the value for comment_reply.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}