package com.handy.support.entity;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_title
     *
     * @mbggenerated
     */
    private String courseTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_intro
     *
     * @mbggenerated
     */
    private String courseIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_note
     *
     * @mbggenerated
     */
    private String courseNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_cover
     *
     * @mbggenerated
     */
    private String courseCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_views
     *
     * @mbggenerated
     */
    private Integer courseViews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_collects
     *
     * @mbggenerated
     */
    private Integer courseCollects;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_likes
     *
     * @mbggenerated
     */
    private Integer courseLikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.diy_label
     *
     * @mbggenerated
     */
    private String diyLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.level_id
     *
     * @mbggenerated
     */
    private Byte levelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Course(Integer courseId, String courseTitle, String courseIntro, String courseNote, String courseCover, Integer courseViews, Integer courseCollects, Integer courseLikes, Integer userId, String diyLabel, Date updateTime, Byte levelId) {
        this.courseId = courseId;
        this.courseTitle = courseTitle;
        this.courseIntro = courseIntro;
        this.courseNote = courseNote;
        this.courseCover = courseCover;
        this.courseViews = courseViews;
        this.courseCollects = courseCollects;
        this.courseLikes = courseLikes;
        this.userId = userId;
        this.diyLabel = diyLabel;
        this.updateTime = updateTime;
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_title
     *
     * @return the value of course.course_title
     *
     * @mbggenerated
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_intro
     *
     * @return the value of course.course_intro
     *
     * @mbggenerated
     */
    public String getCourseIntro() {
        return courseIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_note
     *
     * @return the value of course.course_note
     *
     * @mbggenerated
     */
    public String getCourseNote() {
        return courseNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_cover
     *
     * @return the value of course.course_cover
     *
     * @mbggenerated
     */
    public String getCourseCover() {
        return courseCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_views
     *
     * @return the value of course.course_views
     *
     * @mbggenerated
     */
    public Integer getCourseViews() {
        return courseViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_collects
     *
     * @return the value of course.course_collects
     *
     * @mbggenerated
     */
    public Integer getCourseCollects() {
        return courseCollects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_likes
     *
     * @return the value of course.course_likes
     *
     * @mbggenerated
     */
    public Integer getCourseLikes() {
        return courseLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.user_id
     *
     * @return the value of course.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.diy_label
     *
     * @return the value of course.diy_label
     *
     * @mbggenerated
     */
    public String getDiyLabel() {
        return diyLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.update_time
     *
     * @return the value of course.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.level_id
     *
     * @return the value of course.level_id
     *
     * @mbggenerated
     */
    public Byte getLevelId() {
        return levelId;
    }
}