package com.handy.support.entity;

public class CourseLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_label.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_label.label_id
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    public CourseLabel(Integer courseId, Integer labelId) {
        this.courseId = courseId;
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_label
     *
     * @mbggenerated
     */
    public CourseLabel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_label.course_id
     *
     * @return the value of course_label.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_label.course_id
     *
     * @param courseId the value for course_label.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_label.label_id
     *
     * @return the value of course_label.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_label.label_id
     *
     * @param labelId the value for course_label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }
}