package com.handy.support.entity;

public class CourseItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.item_id
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_item
     *
     * @mbggenerated
     */
    public CourseItem(Integer courseId, Integer itemId) {
        this.courseId = courseId;
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.course_id
     *
     * @return the value of course_item.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.item_id
     *
     * @return the value of course_item.item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }
}