package com.handy.support.entity;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_title
     *
     * @mbggenerated
     */
    private String courseTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_intro
     *
     * @mbggenerated
     */
    private String courseIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_note
     *
     * @mbggenerated
     */
    private String courseNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_cover
     *
     * @mbggenerated
     */
    private String courseCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_views
     *
     * @mbggenerated
     */
    private Integer courseViews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_collects
     *
     * @mbggenerated
     */
    private Integer courseCollects;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_likes
     *
     * @mbggenerated
     */
    private Integer courseLikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.diy_label
     *
     * @mbggenerated
     */
    private String diyLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.level_id
     *
     * @mbggenerated
     */
    private Byte levelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Course(Integer courseId, String courseTitle, String courseIntro, String courseNote, String courseCover, Integer courseViews, Integer courseCollects, Integer courseLikes, Integer userId, String diyLabel, Date updateTime, Byte levelId) {
        this.courseId = courseId;
        this.courseTitle = courseTitle;
        this.courseIntro = courseIntro;
        this.courseNote = courseNote;
        this.courseCover = courseCover;
        this.courseViews = courseViews;
        this.courseCollects = courseCollects;
        this.courseLikes = courseLikes;
        this.userId = userId;
        this.diyLabel = diyLabel;
        this.updateTime = updateTime;
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_title
     *
     * @return the value of course.course_title
     *
     * @mbggenerated
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_title
     *
     * @param courseTitle the value for course.course_title
     *
     * @mbggenerated
     */
    public void setCourseTitle(String courseTitle) {
        this.courseTitle = courseTitle == null ? null : courseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_intro
     *
     * @return the value of course.course_intro
     *
     * @mbggenerated
     */
    public String getCourseIntro() {
        return courseIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_intro
     *
     * @param courseIntro the value for course.course_intro
     *
     * @mbggenerated
     */
    public void setCourseIntro(String courseIntro) {
        this.courseIntro = courseIntro == null ? null : courseIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_note
     *
     * @return the value of course.course_note
     *
     * @mbggenerated
     */
    public String getCourseNote() {
        return courseNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_note
     *
     * @param courseNote the value for course.course_note
     *
     * @mbggenerated
     */
    public void setCourseNote(String courseNote) {
        this.courseNote = courseNote == null ? null : courseNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_cover
     *
     * @return the value of course.course_cover
     *
     * @mbggenerated
     */
    public String getCourseCover() {
        return courseCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_cover
     *
     * @param courseCover the value for course.course_cover
     *
     * @mbggenerated
     */
    public void setCourseCover(String courseCover) {
        this.courseCover = courseCover == null ? null : courseCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_views
     *
     * @return the value of course.course_views
     *
     * @mbggenerated
     */
    public Integer getCourseViews() {
        return courseViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_views
     *
     * @param courseViews the value for course.course_views
     *
     * @mbggenerated
     */
    public void setCourseViews(Integer courseViews) {
        this.courseViews = courseViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_collects
     *
     * @return the value of course.course_collects
     *
     * @mbggenerated
     */
    public Integer getCourseCollects() {
        return courseCollects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_collects
     *
     * @param courseCollects the value for course.course_collects
     *
     * @mbggenerated
     */
    public void setCourseCollects(Integer courseCollects) {
        this.courseCollects = courseCollects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_likes
     *
     * @return the value of course.course_likes
     *
     * @mbggenerated
     */
    public Integer getCourseLikes() {
        return courseLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_likes
     *
     * @param courseLikes the value for course.course_likes
     *
     * @mbggenerated
     */
    public void setCourseLikes(Integer courseLikes) {
        this.courseLikes = courseLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.user_id
     *
     * @return the value of course.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.user_id
     *
     * @param userId the value for course.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.diy_label
     *
     * @return the value of course.diy_label
     *
     * @mbggenerated
     */
    public String getDiyLabel() {
        return diyLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.diy_label
     *
     * @param diyLabel the value for course.diy_label
     *
     * @mbggenerated
     */
    public void setDiyLabel(String diyLabel) {
        this.diyLabel = diyLabel == null ? null : diyLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.update_time
     *
     * @return the value of course.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.update_time
     *
     * @param updateTime the value for course.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.level_id
     *
     * @return the value of course.level_id
     *
     * @mbggenerated
     */
    public Byte getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.level_id
     *
     * @param levelId the value for course.level_id
     *
     * @mbggenerated
     */
    public void setLevelId(Byte levelId) {
        this.levelId = levelId;
    }
}