package com.handy.support.entity;

public class CourseStep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_step.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_step.step_id
     *
     * @mbggenerated
     */
    private Integer stepId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    public CourseStep(Integer courseId, Integer stepId) {
        this.courseId = courseId;
        this.stepId = stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_step
     *
     * @mbggenerated
     */
    public CourseStep() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_step.course_id
     *
     * @return the value of course_step.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_step.course_id
     *
     * @param courseId the value for course_step.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_step.step_id
     *
     * @return the value of course_step.step_id
     *
     * @mbggenerated
     */
    public Integer getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_step.step_id
     *
     * @param stepId the value for course_step.step_id
     *
     * @mbggenerated
     */
    public void setStepId(Integer stepId) {
        this.stepId = stepId;
    }
}