package com.handy.support.entity;

public class Favor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favor.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favor.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    public Favor(Integer userId, Integer courseId) {
        this.userId = userId;
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favor
     *
     * @mbggenerated
     */
    public Favor() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favor.user_id
     *
     * @return the value of favor.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favor.user_id
     *
     * @param userId the value for favor.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favor.course_id
     *
     * @return the value of favor.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favor.course_id
     *
     * @param courseId the value for favor.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}