package com.handy.support.entity;

public class Hot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot.course_hot
     *
     * @mbggenerated
     */
    private Integer courseHot;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbggenerated
     */
    public Hot(Integer courseId, Integer courseHot) {
        this.courseId = courseId;
        this.courseHot = courseHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbggenerated
     */
    public Hot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot.course_id
     *
     * @return the value of hot.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot.course_id
     *
     * @param courseId the value for hot.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot.course_hot
     *
     * @return the value of hot.course_hot
     *
     * @mbggenerated
     */
    public Integer getCourseHot() {
        return courseHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot.course_hot
     *
     * @param courseHot the value for hot.course_hot
     *
     * @mbggenerated
     */
    public void setCourseHot(Integer courseHot) {
        this.courseHot = courseHot;
    }
}