package com.handy.support.entity;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_id
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_number
     *
     * @mbggenerated
     */
    private String itemNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_tag
     *
     * @mbggenerated
     */
    private Integer itemTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated
     */
    public Item(Integer itemId, String itemName, String itemNumber, Integer itemTag) {
        this.itemId = itemId;
        this.itemName = itemName;
        this.itemNumber = itemNumber;
        this.itemTag = itemTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated
     */
    public Item() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_id
     *
     * @return the value of item.item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_id
     *
     * @param itemId the value for item.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_name
     *
     * @return the value of item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_number
     *
     * @return the value of item.item_number
     *
     * @mbggenerated
     */
    public String getItemNumber() {
        return itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_number
     *
     * @param itemNumber the value for item.item_number
     *
     * @mbggenerated
     */
    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber == null ? null : itemNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_tag
     *
     * @return the value of item.item_tag
     *
     * @mbggenerated
     */
    public Integer getItemTag() {
        return itemTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_tag
     *
     * @param itemTag the value for item.item_tag
     *
     * @mbggenerated
     */
    public void setItemTag(Integer itemTag) {
        this.itemTag = itemTag;
    }
}