package com.handy.support.entity;

public class Label {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_id
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_name
     *
     * @mbggenerated
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.flabel_id
     *
     * @mbggenerated
     */
    private Integer flabelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated
     */
    public Label(Integer labelId, String labelName, Integer flabelId) {
        this.labelId = labelId;
        this.labelName = labelName;
        this.flabelId = flabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbggenerated
     */
    public Label() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_id
     *
     * @return the value of label.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_id
     *
     * @param labelId the value for label.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_name
     *
     * @return the value of label.label_name
     *
     * @mbggenerated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_name
     *
     * @param labelName the value for label.label_name
     *
     * @mbggenerated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.flabel_id
     *
     * @return the value of label.flabel_id
     *
     * @mbggenerated
     */
    public Integer getFlabelId() {
        return flabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.flabel_id
     *
     * @param flabelId the value for label.flabel_id
     *
     * @mbggenerated
     */
    public void setFlabelId(Integer flabelId) {
        this.flabelId = flabelId;
    }
}