package com.handy.support.entity;

public class Like {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    public Like(Integer userId, Integer courseId) {
        this.userId = userId;
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    public Like() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.user_id
     *
     * @return the value of like.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.user_id
     *
     * @param userId the value for like.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.course_id
     *
     * @return the value of like.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.course_id
     *
     * @param courseId the value for like.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}