package com.handy.support.entity;

public class Step {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.step_id
     *
     * @mbggenerated
     */
    private Integer stepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.step_tag
     *
     * @mbggenerated
     */
    private Byte stepTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.step_img
     *
     * @mbggenerated
     */
    private String stepImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column step.step_detail
     *
     * @mbggenerated
     */
    private String stepDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated
     */
    public Step(Integer stepId, Byte stepTag, String stepImg, String stepDetail) {
        this.stepId = stepId;
        this.stepTag = stepTag;
        this.stepImg = stepImg;
        this.stepDetail = stepDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table step
     *
     * @mbggenerated
     */
    public Step() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.step_id
     *
     * @return the value of step.step_id
     *
     * @mbggenerated
     */
    public Integer getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.step_id
     *
     * @param stepId the value for step.step_id
     *
     * @mbggenerated
     */
    public void setStepId(Integer stepId) {
        this.stepId = stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.step_tag
     *
     * @return the value of step.step_tag
     *
     * @mbggenerated
     */
    public Byte getStepTag() {
        return stepTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.step_tag
     *
     * @param stepTag the value for step.step_tag
     *
     * @mbggenerated
     */
    public void setStepTag(Byte stepTag) {
        this.stepTag = stepTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.step_img
     *
     * @return the value of step.step_img
     *
     * @mbggenerated
     */
    public String getStepImg() {
        return stepImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.step_img
     *
     * @param stepImg the value for step.step_img
     *
     * @mbggenerated
     */
    public void setStepImg(String stepImg) {
        this.stepImg = stepImg == null ? null : stepImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column step.step_detail
     *
     * @return the value of step.step_detail
     *
     * @mbggenerated
     */
    public String getStepDetail() {
        return stepDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column step.step_detail
     *
     * @param stepDetail the value for step.step_detail
     *
     * @mbggenerated
     */
    public void setStepDetail(String stepDetail) {
        this.stepDetail = stepDetail == null ? null : stepDetail.trim();
    }

    public Step(Byte stepTag, String stepImg, String stepDetail) {
        this.stepTag = stepTag;
        this.stepImg = stepImg;
        this.stepDetail = stepDetail;
    }
}