package com.handy.support.entity;

public class UserAlbum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album.album_id
     *
     * @mbggenerated
     */
    private Integer albumId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    public UserAlbum(Integer userId, Integer albumId) {
        this.userId = userId;
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    public UserAlbum() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album.user_id
     *
     * @return the value of user_album.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album.user_id
     *
     * @param userId the value for user_album.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album.album_id
     *
     * @return the value of user_album.album_id
     *
     * @mbggenerated
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album.album_id
     *
     * @param albumId the value for user_album.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }
}