package com.handy.support.entity;

public class UserLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_label.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_label.label_id
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbggenerated
     */
    public UserLabel(Integer userId, Integer labelId) {
        this.userId = userId;
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_label.user_id
     *
     * @return the value of user_label.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_label.label_id
     *
     * @return the value of user_label.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }
}