package com.handy.support.entity;

import java.util.Date;

public class View {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.view_id
     *
     * @mbggenerated
     */
    private Integer viewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.course_id
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbggenerated
     */
    public View(Integer viewId, Integer userId, Integer courseId, Date updateTime) {
        this.viewId = viewId;
        this.userId = userId;
        this.courseId = courseId;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.view_id
     *
     * @return the value of view.view_id
     *
     * @mbggenerated
     */
    public Integer getViewId() {
        return viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.user_id
     *
     * @return the value of view.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.course_id
     *
     * @return the value of view.course_id
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.update_time
     *
     * @return the value of view.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }
}